### ISSUE TITLE
Error Compile using Less

### ISSUE THREAD

**Issue by viyancs** [advancedrei/BootstrapForEmail#1]
when I'm try to compile bootstrap-email.less using less javascript I have error like this

![Screen Shot 2013-02-20 at 3 38 46 PM](https://f.cloud.github.com/assets/799452/175098/f4740e64-7b38-11e2-86b7-0caa488cdf89.png)

**Comment by robertmclaws** [comment]
You have to put the file in the same folder as your Bootstrap LESS files.
